###############################################################################
# Student Name    : Luke Smith
# RMIT Student ID : S3807720
#
# Startup code provided by Paul Miller for use in "Programming in C",
# Assignment 2, study period 4, 2020.
###############################################################################


